import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, Index, OneToMany } from 'typeorm';
import { OrderStatusEnum, OrderItemTypeEnum, BillingCycleEnum, AddonTypeEnum } from '../../enums/enums';
import { Payment } from './payment.entity';

export interface OrderMetadata {
  type: OrderItemTypeEnum;
  planId?: string;
  planName?: string;
  featureId?: string;
  featureName?: string;
  addonType?: AddonTypeEnum;
  billingCycle?: BillingCycleEnum;
  activationStrategy?: 'immediate' | 'queue' | 'parallel';
}

@Entity({ name: 'orders', schema: 'e_schooling' })
export class Order {
  @PrimaryGeneratedColumn('increment', { type: 'bigint', comment: 'Primary key' })
  id: string;

  @Index()
  @Column({ name: 'school_id', type: 'bigint', nullable: false, comment: 'Reference to School' })
  schoolId: string;

  @Index()
  @Column({ name: 'school_owner_id', type: 'bigint', nullable: false, comment: 'Reference to SchoolOwner' })
  schoolOwnerId: string;

  @Column({ name: 'amount', type: 'decimal', precision: 10, scale: 2, nullable: false, comment: 'Order total amount' })
  amount: number;

  @Column({ name: 'currency', type: 'varchar', length: 10, default: 'INR', comment: 'Currency code' })
  currency: string;

  @Column({ name: 'status', type: 'varchar', default: OrderStatusEnum.PENDING, comment: 'Current order status' })
  status: OrderStatusEnum;

  @Index({ unique: true })
  @Column({ name: 'razorpay_order_id', type: 'varchar', nullable: true, comment: 'ID generated by Razorpay' })
  razorpayOrderId: string;

  @Column({ name: 'metadata', type: 'jsonb', nullable: true, comment: 'Details about what is being purchased' })
  metadata: OrderMetadata;

  @CreateDateColumn({ name: 'created_at', type: 'timestamp' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamp' })
  updatedAt: Date;

  @OneToMany(() => Payment, (payment) => payment.order)
  payments: Payment[];
}
